# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsverifyrecord',
            name='token',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
