# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 14:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MallCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='分类名')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.CreateModel(
            name='MallCommodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='商品名')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('browse_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('stock_count', models.IntegerField(default=666, verbose_name='库存')),
                ('source', models.CharField(default='自拍图', max_length=50, verbose_name='主图来源')),
                ('buy_count', models.IntegerField(default=0, verbose_name='购买量')),
                ('color', models.CharField(max_length=50, verbose_name='颜色')),
                ('model', models.CharField(max_length=100, verbose_name='型号')),
                ('brand', models.CharField(max_length=50, verbose_name='品牌')),
                ('discount', models.FloatField(default=10, verbose_name='折扣')),
                ('description', models.TextField(verbose_name='商品描述')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.MallCategory')),
            ],
            options={
                'verbose_name': '商品名',
                'verbose_name_plural': '商品名',
            },
        ),
        migrations.CreateModel(
            name='MallImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=100, verbose_name='图片名')),
                ('img_url', models.ImageField(upload_to='image/%Y/%m', verbose_name='商品图片')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
            },
        ),
        migrations.AddField(
            model_name='mallcommodity',
            name='image',
            field=models.ManyToManyField(to='mall.MallImages'),
        ),
    ]
